### ISSUE TITLE
Thank you so much for this project.

### ISSUE THREAD

**Issue by asasas234** [vincenzo-racca/spring-webflux-mdc#1]
I am posting here just to thank this project. I am using the webflux + security technology stack, and I want to set the logged-in username in MDC. I have been researching for almost a day without success until I found this library, it saved me!

**Comment by vincenzo-racca** [comment]
@asasas234 thank you :) if you like the project support with a star :)

**Comment by asasas234** [comment]
@vincenzo-racca Already starred
